### ISSUE TITLE
BuildSense reports skipped tests as failing tests

### ISSUE THREAD

**Issue by yoav-orca** [toolchainlabs/issues#1]
**What happens:**
We have python tests that are skipped, BuildSense reports them as failing

**What should happen:**
The tests should be reported as skipped

**Comment by asherf** [comment]
> **What happens:**
> 
> We have python tests that are skipped, BuildSense reports them as failing
> 
> 
> 
> **What should happen:**
> 
> The tests should be reported as skipped

Thanks for the report, I'll be looking into into it.
Just to clarify, do you mean skipped tests that are marked with '@pytest.mark.skip'?

**Comment by asherf** [comment]
sorry for dropping the ball on this.
I think the issue is now fixed.
Feel free to re-open if you still see it.
