### ISSUE TITLE
Feature: BuildSense should link back to the relevant CI

### ISSUE THREAD

**Issue by yoav-orca** [toolchainlabs/issues#3]
**What happens:**
If I open a build in BuildSense I can't get from it back to the relevant CI pipeline, there's no context propagated that can help me find it. The branch / actor helps, but it's still requires me to search many workflows until I find the correct one.

**What I would like to happen:**
I would like to have a link in BuildSense back to the CI pipeline that executed it

**Comment by asherf** [comment]
This should already be the case, buildsense provides links to the CI job and to the SCM (PR or commit for push events)
is that not the case for you?

Is there a specific build where you see it missing?

**Comment by asherf** [comment]
For context, the issue here was that the clickable-area was too small.
this is now fixed.
@yoav-orca I will wait for your feedback here to validate that this works for you before closing the ticket.

**Comment by asherf** [comment]
going to close this out since I believe this is fixed and I haven't heard back.
feel free to reopen.
