### ISSUE TITLE
Feature: "raw" workunits JSON

### ISSUE THREAD

**Issue by joshua-cannon-techlabs** [toolchainlabs/issues#8]
Maybe I want to do more interesting things with the JSON, like various transformations to see flamegraphs or whatever.

**Comment by asherf** [comment]
this is a good idea. we will have this implemented in the next few weeks, we have something similar for internal use, so it shouldn't be that hard to implement this feature for customers.
@benjyw @stuhood fyi

**Comment by asherf** [comment]
@joshua-cannon-techlabs this is now available in the buildsense UI.
Thank you for the suggestion, we appreciate and value your feedback!
<img width="528" alt="Screen Shot 2022-03-02 at 12 03 48 PM" src="https://user-images.githubusercontent.com/1268088/156411395-356bde63-c38b-4712-810f-40cbf4e59f28.png">
<img width="459" alt="Screen Shot 2022-03-02 at 12 03 51 PM" src="https://user-images.githubusercontent.com/1268088/156411397-1e2d82ec-ebe6-484a-b118-8aabe29d00a3.png">
