### ISSUE TITLE
Can you link here on the UI?

### ISSUE THREAD

**Issue by joshua-cannon-techlabs** [toolchainlabs/issues#9]
(Title says it all!)

**Comment by asherf** [comment]
good call!

**Comment by asherf** [comment]
Created an internal issue to track this.
I will update this ticket when this feature ships.

**Comment by asherf** [comment]
shipped.
<img width="409" alt="Screen Shot 2022-01-27 at 11 42 00 AM" src="https://user-images.githubusercontent.com/1268088/151403814-802554e3-9730-4b48-8141-c6d1783b71fc.png">
